[ADD] kakao login 기능 구현
wecode-bootcamp-korea/36-2nd-5MILLION-backend pull request #5
Opened 2022-08-31 15:45 UTC by LeeJ1Hyun

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 로그인 API를 이용한 소셜 로그인  

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카카오 로그인
- 클라이언트로부터 받은 토큰을 이용하여 axios 함수로 카카오 API에 요청을 보내 유저의 nickname, email, id 획득
- id를 이용하여 5MILLION 서비스 자체 accessToken 발급 후 응답으로 반환
- 이미 존재하는 회원이면 error 반환
- 
> 카카오 로그인 DB 결과

![kakao login db result](https://user-images.githubusercontent.com/100523786/187721164-e4d1532d-130a-462c-a559-ab3937ef45a4.png)

>카카오 로그인 후 accessToken 발급 결과 (postman을 이용한 통합 테스트)

![kakao login 후 token 발급 결과](https://user-images.githubusercontent.com/100523786/187721336-a4cb2a19-9a54-409d-8158-21d94da23671.png)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- API 문서에서 원하는 정보를 얻는 능력을 기르게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- kakao_id 컬럼에 저장하는 값이 id인지, 해당 id를 이용하여 accessToken을 발급하는 게 논리적인 로직인지 질문 드립니다.  
공식 문서 혹은 구글 서칭을 해도 해당 내용이 없어서 궁금합니다.

2022-09-01 05:36 UTC, lordmyshepherd requested changes

2022-09-01 05:36 UTC, lordmyshepherd commented on controllers/authController.js
> +    });
`axios.get()` 함수를 실행하고난 후에 반환된 Promise는 `async/await`으로 처리해 주는 것이 가독성에 좋습니다.
then().catch() 보다는 async/await을 사용해서 구현해주세요!

2022-09-01 05:36 UTC, lordmyshepherd commented on controllers/authController.js
> +  axios.get("https://kapi.kakao.com/v2/user/me", {
해당 로직은 controller가 아니라 서비스에 구현해주세요-!

2022-09-01 05:36 UTC, lordmyshepherd commented on controllers/authController.js
> +      const kakaoId = result.data.id.toString();
데이터베이스 컬럼을 string -> int로 변경해주세요~
```suggestion
      const kakaoId = result.data.id;
```

2022-09-01 07:04 UTC, LeeJ1Hyun commented on controllers/authController.js
> +      const kakaoId = result.data.id.toString();
kakao측에서 제공하는 id가 int 자료형 범위를 초과하기 때문에 공식적으로 long타입을 권장하고 있어 int에서 bigint로 자료형을 변경하였습니다.

2022-09-01 07:40 UTC, LeeJ1Hyun commented on controllers/authController.js
> +  axios.get("https://kapi.kakao.com/v2/user/me", {
리뷰 반영하여 service에 구현 했습니다. 세심한 리뷰 감사합니다.

2022-09-01 07:45 UTC, LeeJ1Hyun commented on controllers/authController.js
> +    });
리뷰 반영하여 가독성을 위해 async/await으로 다시 구현하였습니다. 또한 불필요한 async/await은 제거하였습니다. 알려주신 모던 JavaScript 튜토리얼 꼭 정독하겠습니다. 감사합니다.

2022-09-01 11:47 UTC, lordmyshepherd commented on services/authService.js
> +module.exports = { signInWithKakao };
인덴테이션을 잘 맞춰주세요-!

2022-09-01 14:50 UTC, LeeJ1Hyun commented on services/authService.js
> +module.exports = { signInWithKakao };
정렬을 통하여 다시 들여쓰기 조정했습니다. 앞으로 들여쓰기 신경써서 pr 올리겠습니다.

2022-09-02 01:18 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-09-02 01:18 UTC, merged