[ADD] instructors page API 구현 - list page
wecode-bootcamp-korea/36-2nd-5MILLION-backend pull request #7
Opened 2022-09-01 14:52 UTC by isol78

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- instructors list page API 구현. 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- 요청에 따라 list page에 담긴 instructors 데이터를 불러온다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- API의 workflow를 처음으로 이해하고 고민해가며 작성하게 돼서 개인적으로 뜻깊은 시간이었습니다.  

<br />

## :: 기타 질문 및 특이 사항
없습니다. 감사합니다!

2022-09-02 01:27 UTC, lordmyshepherd requested changes

2022-09-02 01:27 UTC, lordmyshepherd commented on controllers/instructorController.js
> +const getInstructors = async (req, res) => {
전체적으로 깔끔합니다!

추가 피드백 드리자면, 데이터 목록(list)를 조회하는 엔드포인트에는 OFFSET과 LIMIT 기능을 추가해주셔야 합니다.

그 이유는 모든 데이터를 조회하게 되면 극단적으로 10만개의 정보를 전부 가져오게되는 것이죠.
그러면 API, 브라우저 메모리에 값을 저장해 놓을 때 부담이 되겠죠?

2022-09-05 13:48 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-09-05 13:48 UTC, merged

2022-09-05 15:05 UTC, isol78 commented on controllers/instructorController.js
> +const getInstructors = async (req, res) => {
네~이번 기회에 OFFSET,LIMIT 처음 알게 되어 공부해서 적용해보는 시간이 생각보다 오래 걸려 힘들면서도 보람찬 시간이었습니다 :)
피드백 감사합니다!!!